### PR TITLE
Added Few Nodes in Documentation (Issue: #16)

### LINKED ISSUE #16: [25 Points Each] Add More Nodes in Documentation
Add Documentation for the following nodes in Docs. (25 Points Each)

- [ ] Extending/Adding Images in Conditionals/Number Input Operators/Input Operators
- [x] Explaining Loop Node
- [x] Explaining Custom Operation Node
- [x] Explaining JS IDE node (use the same node as reference)
- [ ] Add Information Explaining Variables in Editor
- [ ] Add More Example Demos (BMI Calculator)

### PR DESCRIPTION
**Pull request by anupam0-0**
This PR is regarding Issue: #16 

I have added the following nodes in the documentation:
 -Explaining Loop Node
 -Explaining Custom Operation Node
 -Explaining JS IDE node (use the same node as reference)
 -Add Information Explaining Variables in Editor
 
 This is my first PR in this repo, so I went with the easiest one I could have found.
 Pls, guide me and rectify, where I did smthng wrong.
 
 Thank You

### CODE REVIEW

**Review by Sarfraz-droid — APPROVED** [review]

**Comment by Sarfraz-droid** [comment]
@Anupam0-0 "Add Information Explaining Variables in Editor" These changes hasn't been added yet. Are you planning to add those as well?

**Comment by anupam0-0** [comment]
I have added 'variables'...

**Review by Sarfraz-droid — APPROVED** [review]

**Comment by Sarfraz-droid** [comment]
give @Anupam0-0 100 points

**Comment by pranshu05** [comment]
give @Anupam0-0 100 points

**Pull request merged**
